version: '3'


services:
  db:
    image: postgres:14.3
    restart: on-failure
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
